/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.event.MouseListener;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import logica.controladores.IControladorUsuario;
import logica.controladores.IControladorVideo;

/**
 *
 * @author pagol
 */
public class registroVideo extends javax.swing.JInternalFrame {
static String VideoRegister;
static String x;
IControladorVideo v;
IControladorUsuario u;
    /**
     * Creates new form registroVideo
     */
    public registroVideo(IControladorVideo Video, IControladorUsuario usuario) {
        initComponents();
        setVisible(true);
        setTitle("Videos");
        setClosable(true);
        
        //Spinner model aca
        SpinnerNumberModel modeloSpinner = new SpinnerNumberModel();
        //modeloSpinner.setMaximum(60);
        modeloSpinner.setMinimum(0);
        jSpinner1.setModel(modeloSpinner);
        
        SpinnerNumberModel modeloSpinner2 = new SpinnerNumberModel();
        modeloSpinner2.setMaximum(60);
        modeloSpinner2.setMinimum(0);
        jSpinner2.setModel(modeloSpinner2);
        
        VideoRegister="opened";
        v=Video;
        u=usuario;
        obtenerCategorias();
        BasicInternalFrameUI basicInternalFrameUi = ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI());
        for(MouseListener listener:basicInternalFrameUi.getNorthPane().getMouseListeners()){
        basicInternalFrameUi.getNorthPane().removeMouseListener(listener);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField4 = new java.awt.TextField();
        label4 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        textField1 = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        textField6 = new java.awt.TextField();
        label6 = new java.awt.Label();
        label5 = new java.awt.Label();
        CategoriasBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        label7 = new java.awt.Label();

        setClosable(true);
        setMinimumSize(new java.awt.Dimension(393, 34));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 113, 112, -1));

        label4.setText("Descripcion");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 113, -1, -1));

        jButton1.setText("Registrar");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        getContentPane().add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 23, 112, -1));

        label1.setText("Nombre");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 23, -1, -1));

        label2.setText("Duracion");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 53, -1, -1));

        label3.setText("UrlAsociada");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 83, -1, -1));

        textField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField3ActionPerformed(evt);
            }
        });
        getContentPane().add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 112, -1));
        getContentPane().add(textField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 173, 112, -1));

        label6.setText("User");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 173, -1, -1));

        label5.setText("Categoria");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 143, 70, -1));
        label5.getAccessibleContext().setAccessibleName("Categoria (opcional)");

        CategoriasBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna" }));
        CategoriasBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriasBoxActionPerformed(evt);
            }
        });
        getContentPane().add(CategoriasBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 143, 112, -1));

        jButton2.setText("Cancelar");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 53, 55, -1));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 53, 50, -1));

        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setText(":");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        VideoRegister=null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {       
            //Creo el video
            v.AltaVideo(
                    textField1.getText(),
                    jSpinner1.getValue().toString()+"."+jSpinner2.getValue().toString(),
                    textField3.getText(), 
                    textField4.getText(),
                    u.obtenerIdUsuario(textField6.getText()),
                    CategoriasBox.getSelectedItem().toString()
            );
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CategoriasBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriasBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriasBoxActionPerformed

    private void textField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField3ActionPerformed

    private void obtenerCategorias() {
        List cts = u.obtenerCategorias();
        Iterator it = cts.iterator();
        
        while(it.hasNext()){
            CategoriasBox.addItem((String)it.next());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CategoriasBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.TextField textField1;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField6;
    // End of variables declaration//GEN-END:variables
}
