/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;


import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.event.MouseListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import logica.controladores.Fabrica;
import logica.controladores.IControladorUsuario;
import org.apache.commons.io.FileUtils;
/**
 *
 * @author pagol
 */
public class registroUser extends javax.swing.JInternalFrame {
    
    Fabrica fab = Fabrica.getInstance();
    static String x;
    UyTubeFrame p;
    IControladorUsuario u;
    JFileChooser fc;
    /**
     * Creates new form registroUser
     */
    public registroUser(UyTubeFrame padre) {
        initComponents();
        setVisible(true);
        setTitle("Usuarios");
        setClosable(true);
        x="opened";
        u=fab.getIControladorUsuario();
        p=padre;
        fc = new JFileChooser();
        fc.setVisible(false);
        JTextFieldDateEditor editor = (JTextFieldDateEditor) jDateChooser1.getDateEditor();
        editor.setEditable(false);
        
        BasicInternalFrameUI basicInternalFrameUi = ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI());
        for(MouseListener listener:basicInternalFrameUi.getNorthPane().getMouseListeners()){
        basicInternalFrameUi.getNorthPane().removeMouseListener(listener);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelar = new javax.swing.JButton();
        textField1 = new java.awt.TextField();
        label1 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        textField4 = new java.awt.TextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        textField6 = new java.awt.TextField();
        label6 = new java.awt.Label();
        jButtonSubir = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        textField5 = new java.awt.TextField();

        setClosable(true);
        setMinimumSize(new java.awt.Dimension(381, 324));
        setName(""); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        getContentPane().add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 23, 79, -1));

        label1.setText("Nombre");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 23, -1, -1));
        getContentPane().add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 53, 79, -1));

        label2.setText("Apellido");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 53, -1, -1));
        label2.getAccessibleContext().setAccessibleName("Nombre2");

        label3.setText("Nickname");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 83, -1, -1));
        getContentPane().add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 79, -1));
        getContentPane().add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 79, -1));

        label4.setText("Email");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        label5.setText("Fecha de nacimiento");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        textField6.setEditable(false);
        getContentPane().add(textField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 77, -1));

        label6.setText("Imagen");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jButtonSubir.setText("Subir");
        jButtonSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, 20));

        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 122, -1));

        jLabel1.setText("Contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        getContentPane().add(textField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 79, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        x=null;
        u=null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        JOptionPane.showMessageDialog(null,"El registro ha sido cancelado");
        x=null;
        u=null;
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubirActionPerformed
        fc.setVisible(true);
        fc.showOpenDialog(null);
        File f = fc.getSelectedFile();
        String fpath = f.getAbsolutePath();
        textField6.setText(fpath);
    }//GEN-LAST:event_jButtonSubirActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        //Mover a registrarCanal
        try {
            // Me aseguro de que la imagen es correcta y la guardo
            File f = fc.getSelectedFile();
            String imagen = "";
            String fpath = "";
            String fnewpath = "";
            if(f != null){
                fpath = f.getPath();
                String extension = "";
                int i = fpath.lastIndexOf('.');
                if (i > 0) extension = fpath.substring(i+1);

                if (!extension.equals("jpg") && !extension.equals("png"))
                    throw new Exception(extension+" Imagen con extension invalida, por favor suba una imagen .jpg o .png");

                imagen = textField3.getText() + "." + extension;
                fnewpath = "data/imagenes/" + imagen;
            }
            //AltaUsuario(String nick,String passw, String nom, String apell, String mail, Date fnac, String img)
            //Creo el usuario
            int existe = u.obtenerIdUsuario(textField3.getText());
            u.AltaUsuario(
                textField3.getText(),
                textField5.getText(),    
                textField1.getText(),
                textField2.getText(), 
                textField4.getText(),
                jDateChooser1.getDate(),
                imagen
            );
            
            //Copio el archivo al directorio de imagenes, lo hago luego por si el nick ya existe
            if(!fpath.equals(fnewpath) && !fnewpath.isEmpty()) FileUtils.copyFile(f, new File(fnewpath));
            
            if(existe != u.obtenerIdUsuario(textField3.getText())) {
                p.AgregarInternalFrame(new registroCanal(textField3.getText()));
                x=null;
                u=null;
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JButton jButtonSubir;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    // End of variables declaration//GEN-END:variables
}
