
package logica.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WScontroladorVideo", targetNamespace = "http://webservices.logica/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WScontroladorVideo {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.logica/WScontroladorVideo/probandoRequest", output = "http://webservices.logica/WScontroladorVideo/probandoResponse")
    public String probando(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     */
    @WebMethod(operationName = "ModificarVideo")
    @Action(input = "http://webservices.logica/WScontroladorVideo/ModificarVideoRequest", output = "http://webservices.logica/WScontroladorVideo/ModificarVideoResponse")
    public void modificarVideo(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        XMLGregorianCalendar arg5,
        @WebParam(name = "arg6", partName = "arg6")
        boolean arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod(operationName = "ValorarVideo")
    @Action(input = "http://webservices.logica/WScontroladorVideo/ValorarVideoRequest", output = "http://webservices.logica/WScontroladorVideo/ValorarVideoResponse")
    public void valorarVideo(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        boolean arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod(operationName = "ComentarVideo")
    @Action(input = "http://webservices.logica/WScontroladorVideo/ComentarVideoRequest", output = "http://webservices.logica/WScontroladorVideo/ComentarVideoResponse")
    public void comentarVideo(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        long arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        XMLGregorianCalendar arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns logica.webservices.VideoDt
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.logica/WScontroladorVideo/obtenerVideoDtRequest", output = "http://webservices.logica/WScontroladorVideo/obtenerVideoDtResponse")
    public VideoDt obtenerVideoDt(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @return
     *     returns logica.webservices.PojoVideoDt
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.logica/WScontroladorVideo/obtenerVideosRequest", output = "http://webservices.logica/WScontroladorVideo/obtenerVideosResponse")
    public PojoVideoDt obtenerVideos();

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.webservices.VideoDt
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.logica/WScontroladorVideo/obtenerVideoDtPorIDRequest", output = "http://webservices.logica/WScontroladorVideo/obtenerVideoDtPorIDResponse")
    public VideoDt obtenerVideoDtPorID(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.webservices.PojOvaloracionDt
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.logica/WScontroladorVideo/obtenerValoracionVideoRequest", output = "http://webservices.logica/WScontroladorVideo/obtenerValoracionVideoResponse")
    public PojOvaloracionDt obtenerValoracionVideo(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.webservices.PojoComentarioDt
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.logica/WScontroladorVideo/obtenerComentariosDtRequest", output = "http://webservices.logica/WScontroladorVideo/obtenerComentariosDtResponse")
    public PojoComentarioDt obtenerComentariosDt(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.webservices.VideoDt
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.logica/WScontroladorVideo/obtenerVideoDtPorCODRequest", output = "http://webservices.logica/WScontroladorVideo/obtenerVideoDtPorCODResponse")
    public VideoDt obtenerVideoDtPorCOD(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod(operationName = "AltaVideo")
    @Action(input = "http://webservices.logica/WScontroladorVideo/AltaVideoRequest", output = "http://webservices.logica/WScontroladorVideo/AltaVideoResponse")
    public void altaVideo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5);

    /**
     * 
     * @return
     *     returns logica.webservices.ComentarioDt
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.logica/WScontroladorVideo/pruebaComentarioDtRequest", output = "http://webservices.logica/WScontroladorVideo/pruebaComentarioDtResponse")
    public ComentarioDt pruebaComentarioDt();

}
