
package logica.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WScontroladorCategoria", targetNamespace = "http://webservices.logica/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WScontroladorCategoria {


    /**
     * 
     * @return
     *     returns logica.webservices.PojoCategoriaDt
     */
    @WebMethod(operationName = "ListarCategorias")
    @WebResult(partName = "return")
    @Action(input = "http://webservices.logica/WScontroladorCategoria/ListarCategoriasRequest", output = "http://webservices.logica/WScontroladorCategoria/ListarCategoriasResponse")
    public PojoCategoriaDt listarCategorias();

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.webservices.CategoriaDt
     */
    @WebMethod(operationName = "ConsultarCategorias")
    @WebResult(partName = "return")
    @Action(input = "http://webservices.logica/WScontroladorCategoria/ConsultarCategoriasRequest", output = "http://webservices.logica/WScontroladorCategoria/ConsultarCategoriasResponse")
    public CategoriaDt consultarCategorias(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "AltaCategoria")
    @Action(input = "http://webservices.logica/WScontroladorCategoria/AltaCategoriaRequest", output = "http://webservices.logica/WScontroladorCategoria/AltaCategoriaResponse")
    public void altaCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.webservices.PojoListadrDt
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.logica/WScontroladorCategoria/obtenerListasDtCategoriaRequest", output = "http://webservices.logica/WScontroladorCategoria/obtenerListasDtCategoriaResponse")
    public PojoListadrDt obtenerListasDtCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.webservices.PojoVideoDt
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.logica/WScontroladorCategoria/obtenerVideosDtCategoriaRequest", output = "http://webservices.logica/WScontroladorCategoria/obtenerVideosDtCategoriaResponse")
    public PojoVideoDt obtenerVideosDtCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
